---
sudo: required
branches:
  only:
    - dev
language: python
# python:
#   - "2.7"
#   - "3.6"
# launch two jobs and execute the tests for each environment in parallel
matrix:
    include:
      - python: 2.7
        # env: TOX_ENV=py27
      - python: 3.6
        # env: TOX_ENV=py36
dist: bionic
services:
- docker
cache:
  directories:
    - $HOME/.cache/pip
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
before_install:
# install goss
- sudo apt-get -qq update
# - virtualenv --python=$(which python3.6) envgoss
# - source envgoss/bin/activate
- pip install -r requirements.txt
- curl -L https://goss.rocks/install | sudo sh
install:
- bash bootstrap.sh
- pip install tox
# Travis provides the python version for each test as TRAVIS_PYTHON_VERSION,
# but in the form '3.4', while tox expects 'py34'
# If you don't want to rely on an external lib (tox-travis) to do the translation, you can do that manually
# - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
# This works for pypy Source: flask-mongoengine's .travis.yml.
# - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/')
script:
- make build
- docker image ls
- docker container ls -a
